### ISSUE TITLE
No autocompletion inside autoclosed pairs

### ISSUE THREAD

**Issue by kopischke** [laughedelic/pisces#1]
Not sure if there is much _pisces_ can do about it, but fish completion breaks inside autocompleted pairs, probably because the closing symbol is then added to the tokens parsed for completion. Without _pisces_

```fish
echo "$<tab>
```

will complete variable names, but with it

```fish
echo "$<tab>"
```

will offer no completions.

**Comment by laughedelic** [comment]
@kopischke I see the problem, but it's not caused by pisces. I mean that if you uninstall pisces and reproduce the same situation, you won't get completions. Probably it's worth creating an issue in the fish-shell repo.
Anyway, I'll think of a workaround.

**Comment by kopischke** [comment]
Yes, I am aware that the issue is not **caused** by _pisces_ (I never said otherwise); the reason I do not consider this a _fish_ issue, but one _pisces_ needs to address, still stand: 

1. users are highly unlikely to add closing pair characters before trying to complete without _pisces_, and
2. it means _pisces_’ is only of use if you are willing to trade it for one of _fish’s most powerful features.

**Comment by laughedelic** [comment]
@kopischke sure, I understand your arguments and I see how pisces brings this issue to the surface.

Here's one probably ~~un~~related observation: if I understand right, `complete` works on the current _token_:

> `complete`, guess the remainder of the current token  (from `man bind`)

```fish
echo "$|"
```
(`|` is the cursor position)

In fish 2.2 `commandline --current-token` returns `$` (ignoring quotes, see https://github.com/fish-shell/fish-shell/issues/2210), while in 2.3 it returns `"$"`. Which version of fish do you use?

**Comment by kopischke** [comment]
I’m using _fish_ 2.3 beta 2, and yes, you need an extra char to get a completion.

**Comment by laughedelic** [comment]
@kopischke I had some [chat](https://gitter.im/fish-shell/fish-shell?at=5733116bed393f3409b1ca8b) with a fish developer and it doesn't seem solvable by providing some custom completion handling, because you cannot just call _pager_ to complete a given string (so it's accessible only internally).

I've made a little demo of what's doable: [completing vars inside of double quotes](https://asciinema.org/a/45270). As you see, when there's only one option, it's easy and nice, but if there are several, I cannot invoke normal fish completion in place. There are different workarounds: 
- in the demo I use [choices](https://github.com/fisherman/choices)
- just list available options so that you can continue typing until you get a single completion
- external tools like [fzf](https://github.com/junegunn/fzf) can be used (optinally)

What do you think about it?

Another stupid, but very **simple** workaround just for the particular type of situations as in your example: 
1. `echo $P|<TAB>`, you get the completed var: `echo $PATH |`
2. cut it with `<Ctrl>+W`, you have now just `echo |`
3. type `"`, now you're inside the quotes pair
4. yank the var with `<Ctrl>+Y`, you have: `echo "$PATH |"`

**Comment by kopischke** [comment]
Well, that is a pity, albeit not entirely unexpected. I am afraid that means I will have to pass on using _pisces_: omnipresent, uncomplicated, quasi magical auto completion is what sold me on _fish_; even the nicest plugin (and _pisces_ is very nice) is not worth compromising that. Would you like to keep the issue open to track it or shall I close?

**Comment by laughedelic** [comment]
Sure, I'll keep it open. As I see it, _pisces_ causes problems only when initially typing text, because if you  already have a double quoted string (with or without pisces), you cannot autocomplete anything inside of it. A workaround could be to bind the <kbd>tab</kbd> key to delete `"` in front of the cursor  (if there is one) and call `complete`: so you get autocomplete and have to close the quotes manually as if you didn't use _pisces_, while in other cases it still works as before. Do you think this could be useful?

> I am afraid that means I will have to pass on using pisces

If the only problem is about double quotes and you don't want any of  the suggested workarounds, why not just disabling this particular pair, while keeping the rest? There is a setting for that:

```
> echo $pisces_pairs
(,) [,] {,} "," ','
> set -e pisces_pairs[4]
> echo $pisces_pairs
(,) [,] {,} ','
```

You can just [set](https://github.com/laughedelic/pisces#changing-the-set-of-pairs) it as you like.

Or do you have more similar issues?

**Comment by laughedelic** [comment]
>  A workaround could be to bind the <kbd>tab</kbd> key to delete " in front of the cursor (if there is one) and call complete: so you get autocomplete ~~and have to close the quotes manually as if you didn't use pisces~~, while in other cases it still works as before.

A little demo of this overriden <kbd>tab</kbd>:
![pisces_tab](https://cloud.githubusercontent.com/assets/766656/15251811/73e92f6a-192b-11e6-8d4d-d47770d78bc2.gif)

A curious thing about fish completion is that after completing a token that starts with `"`, it closes quotes automatically, so you don't need to do anything 👍 
@kopischke if this works for you, I will add it in the next release.

**Comment by kopischke** [comment]
@laughedelic now that sounds like an excellent workaround. Would love to see that make the next release.

**Comment by laughedelic** [comment]
@kopischke you can try it  😉  `fisher up pisces`

**Comment by kopischke** [comment]
@laughedelic very nice, I’m in love with _pisces_ again. I stumbled on an issue with the new completion wrapper, though, see #2.
