### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by levthedev** [laughedelic/pisces#7]
I've noticed that with Pisces installed in my (fairly minimally configured) fish shell, I get keypress performance issues.

Specifically, if I type a string with a couple of Pisces pairs, such as `echo "()foobar[]()foobar[]()foobar[]()foobar[]"`, then try to delete some characters (by holding down delete), my shell lags considerably. It usually takes a few hundred ms after I let of the backspace key before it stops deleting. If I uninstall Pisces, then backspacing is instant, no matter what string I am backspacing and for how long.

I am using iTerm 2, if that matters.

For me, the performance issue means that Pisces is not worth using. Is there anyway this could be fixed? I looked at the backspace function and it seems pretty minimal, so I'm not sure how it could be improved.

Also, thanks so much for developing this plugin - I don't mean to complain. I just want to let you know about the performance issues in case you didn't already.

**Comment by laughedelic** [comment]
Hi @levthedev! I'm glad that you like the plugin and I'm sad to hear that it causes you troubles.

I tried your example and I don't notice any significant delay. I'm also using iTerm, Fish v2.6. 
Could you tell me a bit more about your setting? What other plugins do you use? Any heavy custom configuration? Also any more examples where this delay is very noticeable would be helpful for me. 

Even if there is no any general solution, I have a workaround suggestion for you:
- you could reduce the number of paired symbols (see [here](https://github.com/laughedelic/pisces#changing-the-set-of-pairs)), because the backspace override function goes through all of them each time you press the key. If you don't use, for example `{,}`, you could remove it and see if there is any improvement.
- you could also completely cancel the backspace override, but use the rest of the plugin features

Let me know what you think about it.

**Comment by agb80** [comment]
I'm also having performance issues with pisces, I'm using tilda and Fish v2.7

Here is a list of installed plugins if that helps you, no custom configuration nor nothing else than this plugins:

* metro
* git_util
* last_job_id
* segment
* z
* bd
* host_info
* pwd_info
* ssh
getopts			humanize_duration	pwd_is_home		sudope

**Comment by laughedelic** [comment]
@nickeb96 cool 👍 thanks for sharing. I'd appreciate some feedback from @levthedev or @agb80 to see if your patch solves their issues as well.

**Comment by jorgebucaran** [comment]
Anyone looking at this, the new way to install packages with fisher is using the `add` command.

```
fisher add nickeb96/pisces
```

@laughedelic Yup, I can notice @nickeb96's fork is faster, but I'm not sure if I am testing the right things since I don't normally use this package.

Cheers.

**Comment by mienaikage** [comment]
I was having performance issues when using backspace, and @nickeb96 's fork has resolved this for me.

**Comment by Jomik** [comment]
@nickeb96 Mind throwing that PR here? I'd prefer pointing at a single repo :+1:

**Comment by laughedelic** [comment]
Thanks everyone for the feedback and especially to @nickeb96 for the solution. It's in master now, so you should get it next time you update the plugin.
