### ISSUE TITLE
Tab Completion

### ISSUE THREAD

**Issue by hamon-e** [laughedelic/pisces#8]
This command broke circular tab completion

`bind -M $_pisces_bind_mode \t _pisces_complete`

See this example,
(first command pressing lot of TAB)
(second command pressiong lot of SHIFT-TAB)
https://asciinema.org/a/bShqIYrla3TCMwILAyAZShYRs

As we can see the first completion doesn't return to the beginning

**Comment by laughedelic** [comment]
Hi @hamon-e! This reminds me of an issue I opened in the fish-shell repo a time ago: https://github.com/fish-shell/fish-shell/issues/4331. So the problem comes from some general inconsistencies in the Fish pager. You can see that `_pisces_complete` function uses builtin `down-or-serach` when in the pager:

https://github.com/laughedelic/pisces/blob/6f251099bdd30bf08ae4f8bdd3f6167379a4d310/functions/_pisces_complete.fish#L3-L5

It's used by ^N in the standard keybindings. So I think the problem with navigation is in that function.

I guess, I didn't notice that the plugin makes it worse, because I usually use ^N/^P to navigate completions and it behaves the same with or without pisces. I agree that it's annoying, but I don't have a workaround at the moment, except of rebinding `\t` back in your config:

```shell
bind \t complete
```

(with `-M insert` if you're using vi/hybrid keybindings)

It would be nice if you reported this problem back to the fish-shell repo. Or at least comment on that old issue to draw some attention to it again.

**Comment by laughedelic** [comment]
Great! I'm closing it here then. It seems that https://github.com/fish-shell/fish-shell/pull/4680 should fix it in Fish v3.0.
